// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PcAssistant.Persistence;

#nullable disable

namespace PcAssistant.Persistence.Migrations
{
    [DbContext(typeof(PcAssistantDbContext))]
    [Migration("20260704060742_AddChatSessions")]
    partial class AddChatSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("PcAssistant.Domain.ChatSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("chat_sessions", (string)null);
                });

            modelBuilder.Entity("PcAssistant.Domain.CommandLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssistantMessage")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChatSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommandLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExecutedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutionMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDangerous")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Preview")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawPredictedLabel")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequiresConfirmation")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResolvedPath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatSessionId");

                    b.HasIndex("CreatedAtUtc");

                    b.ToTable("command_logs", (string)null);
                });

            modelBuilder.Entity("PcAssistant.Domain.CommandLogEntry", b =>
                {
                    b.HasOne("PcAssistant.Domain.ChatSession", null)
                        .WithMany("CommandLogs")
                        .HasForeignKey("ChatSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PcAssistant.Domain.ChatSession", b =>
                {
                    b.Navigation("CommandLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
